global:
  scrape_interval: 15s # intervalo da coleta
  evaluation_interval: 15s # alertas

rule_files:
scrape_configs:
  - job_name: "prometheus"
    static_configs: 
      - targets: ["localhost:9090"]
