groups:
  - name: Meus primeiros alertas
    rules:
    - alert: LoadAverage
      expr: node_load1 > 0.5
      for: 1m
      annotations:
        title: ' A {{ $labels.instance }} está com o load_average alto'
        description: ' Faça alguma coisa Mutly '
        summary: ' {{ $labels.instance }} está com o load alto'
        value: '{{ $value }}'
      labels:
        severity: 'critical'
    - alert: DiskUsage
      expr: (node_filesystem_size_bytes - node_filesystem_free_bytes ) * 100 / node_filesystem_size_bytes > 70.0
      for: 1m
      labels:
        instance: '{{ $labels.instance }}:{{ $labels.mountpoint }}'
      annotations:
        value: '{{ humanize $value  }}'