global:
  resolve_timeout: 5m
  slack_api_url: '<webkook>'
time_intervals: 
  - name: workdays
    time_intervals:
      - weekdays ['monday:friday']
  - name: workhours
    time_intervals:
      - times: 
        - start_time: 09:00
          end_time: 18:00
  
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack'
  routes: 
  - receiver: 'alertas-email'
    group_wait: 30s
    matchers:
      - alertname = DiskUsage
    group_by: ['alertname', 'instance']
    active_time_interval:
      - workdays
      - workhours

receivers:
  - name: 'slack'
    slack_configs:
    - channel: '#alerts'
      send_resolved: true
  - name: 'alertas-email'
    email_configs: 
    - to: cquinta@gmail.com
      from: cquinta@gmail.com
      smarthost: smtp.gmail.com:587
      auth_username: cquinta@gmail.com
      auth_identity: cquinta@gmail.com
      auth_password: <senha_de_app>
      send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

      

    
      
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']