global:
  resolve_timeout: 5m
  slack_api_url: '<webkook>'
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'slack'
receivers:
  - name: 'slack'
    slack_configs:
    - channel: '#alerts'
    send_resolved: true
    title: |-
      [{{ .Status | to Upper }}{{ if eq .Status "firint" }}:{{ .Alerts.Firing | len }} {{ end }}] {{ .CommonLabels.alertname }} na instancia {{ .CommonLabels.instance }}
    text: >-
      {{ range .Alerts -}}
      *Alerta: * {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .labels.severity }}`{{ end }}
       
    
      
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']